apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "social-automation.fullname" . }}-config
  labels:
    {{- include "social-automation.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  PORT: "3000"
  NEXT_TELEMETRY_DISABLED: "1"
  NEXT_PUBLIC_APP_URL: {{ .Values.ingress.hosts | first | default dict | pluck "host" | first | default "http://localhost:3000" | quote }}
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
