apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-automation.fullname" . }}-web
  labels:
    {{- include "social-automation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "social-automation.selectorLabels" . | nindent 4 }}
    app: app-web
