'use client';

import { useState, useEffect } from 'react';
import { Sparkles, CheckCircle2, RotateCcw, AlertTriangle, Edit3, Save, ThumbsUp, ThumbsDown, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { motion } from 'framer-motion';
import { 
  getBusinessSummary, 
  generateBusinessSummaryAI, 
  approveBusinessSummary, 
  updateBusinessSummaryOverride 
} from '../actions';

export function KnowledgeSummary() {
  const [summary, setSummary] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [isApproving, setIsApproving] = useState(false);

  const [editForm, setEditForm] = useState({
    shortSummary: '',
    detailedOverview: '',
    elevatorPitch: '',
    marketingPositioning: ''
  });

  const loadSummary = async () => {
    try {
      setIsLoading(true);
      const data = await getBusinessSummary();
      setSummary(data);
      if (data) {
        setEditForm({
          shortSummary: data.shortSummary || '',
          detailedOverview: data.detailedOverview || '',
          elevatorPitch: data.elevatorPitch || '',
          marketingPositioning: data.marketingPositioning || ''
        });
      }
    } catch (e) {
      toast.error('Failed to load Brand DNA Canvas');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadSummary();
  }, []);

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const result = await generateBusinessSummaryAI();
      setSummary(result);
      setEditForm({
        shortSummary: result.shortSummary || '',
        detailedOverview: result.detailedOverview || '',
        elevatorPitch: result.elevatorPitch || '',
        marketingPositioning: result.marketingPositioning || ''
      });
      toast.success('Brand DNA Canvas generated by AI successfully!');
    } catch (e: any) {
      toast.error(e.message || 'Failed to generate Brand DNA Canvas');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleApprove = async (approve: boolean) => {
    setIsApproving(true);
    try {
      const result = await approveBusinessSummary(approve);
      setSummary(result);
      toast.success(approve ? 'Brand DNA Canvas approved for generation!' : 'Approval revoked.');
    } catch (e) {
      toast.error('Failed to update approval status');
    } finally {
      setIsApproving(false);
    }
  };

  const handleSaveOverride = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSaving(true);
    try {
      const result = await updateBusinessSummaryOverride(editForm);
      setSummary(result);
      setIsEditing(false);
      toast.success('Brand DNA override successfully saved!');
    } catch (e) {
      toast.error('Failed to save manual summary override');
    } finally {
      setIsSaving(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center p-12 min-h-[300px]">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  const cardClasses = "rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900/50 hover:shadow-md transition-all";
  const labelClasses = "block text-xs font-black uppercase tracking-wider text-slate-400 dark:text-slate-500 mb-2";

  return (
    <div className="space-y-8">
      {/* Banner/Header with status controls */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-6 rounded-3xl bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-950/20 dark:to-indigo-950/20 border border-blue-100 dark:border-blue-900/30">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-blue-500/10 rounded-2xl">
            <Sparkles className="h-6 w-6 text-blue-600 dark:text-blue-400" />
          </div>
          <div>
            <h3 className="font-bold text-slate-900 dark:text-white">AI-Powered Brand DNA Summaries</h3>
            <p className="text-sm text-slate-600 dark:text-slate-400">
              {summary ? (
                summary.isApproved ? (
                  <span className="text-emerald-600 dark:text-emerald-400 font-medium flex items-center gap-1.5 mt-0.5">
                    <CheckCircle2 className="h-4 w-4" /> Approved for Content Generation RAG Context
                  </span>
                ) : (
                  <span className="text-amber-600 dark:text-amber-400 font-medium flex items-center gap-1.5 mt-0.5">
                    <AlertTriangle className="h-4 w-4" /> Pending Approval (using default brand properties)
                  </span>
                )
              ) : "No summaries generated yet."}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto">
          {summary && (
            <>
              <button
                onClick={() => setIsEditing(!isEditing)}
                disabled={isGenerating || isApproving || isSaving}
                className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 hover:bg-slate-50 dark:hover:bg-slate-800 text-sm font-bold disabled:opacity-50 transition-all"
              >
                <Edit3 className="h-4 w-4" /> {isEditing ? 'Cancel Edit' : 'Override DNA'}
              </button>
              
              <button
                onClick={() => handleApprove(!summary.isApproved)}
                disabled={isGenerating || isApproving || isSaving}
                className={`flex-1 sm:flex-none flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl text-sm font-black disabled:opacity-50 transition-all ${
                  summary.isApproved
                    ? 'bg-amber-100 hover:bg-amber-200 text-amber-800 dark:bg-amber-950/40 dark:text-amber-400'
                    : 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-md'
                }`}
              >
                {isApproving ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : summary.isApproved ? (
                  <ThumbsDown className="h-4 w-4" />
                ) : (
                  <ThumbsUp className="h-4 w-4" />
                )}
                {isApproving 
                  ? (summary.isApproved ? 'Revoking...' : 'Approving...') 
                  : (summary.isApproved ? 'Revoke Approval' : 'Approve DNA')}
              </button>
            </>
          )}

          <button
            onClick={handleGenerate}
            disabled={isGenerating || isApproving || isSaving}
            className="flex-1 sm:flex-none flex items-center justify-center gap-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 disabled:opacity-50 text-white px-5 py-2.5 rounded-xl text-sm font-black shadow-lg shadow-blue-500/10 transition-all"
          >
            {isGenerating ? (
              <span className="flex items-center gap-1.5"><Loader2 className="h-4 w-4 animate-spin" /> Analyzing Brand...</span>
            ) : (
              <><Sparkles className="h-4 w-4" /> Generate DNA Canvas</>
            )}
          </button>
        </div>
      </div>

      {/* Editing State */}
      {isEditing ? (
        <form onSubmit={handleSaveOverride} className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm dark:border-slate-800 dark:bg-slate-900/50 space-y-6">
          <div className="flex items-center justify-between pb-4 border-b border-slate-200 dark:border-slate-800">
            <h4 className="font-black text-lg text-slate-900 dark:text-white">Override Brand DNA Canvas</h4>
            <span className="text-xs font-semibold px-3 py-1 rounded-full bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400">Manual Override Mode</span>
          </div>

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Elevator Pitch</label>
              <input
                type="text"
                className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-slate-900 focus:border-blue-500 focus:outline-none focus:ring-4 focus:ring-blue-500/10 dark:border-slate-800 dark:bg-slate-900 dark:text-white transition-all"
                value={editForm.elevatorPitch}
                onChange={e => setEditForm(prev => ({ ...prev, elevatorPitch: e.target.value }))}
                placeholder="Punchy, 1-2 sentence hook..."
                required
              />
            </div>

            <div>
              <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Short Brand Summary</label>
              <textarea
                rows={3}
                className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-slate-900 focus:border-blue-500 focus:outline-none focus:ring-4 focus:ring-blue-500/10 dark:border-slate-800 dark:bg-slate-900 dark:text-white transition-all"
                value={editForm.shortSummary}
                onChange={e => setEditForm(prev => ({ ...prev, shortSummary: e.target.value }))}
                placeholder="Dense brand summary in 50-100 words..."
                required
              />
            </div>

            <div>
              <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Detailed Overview</label>
              <textarea
                rows={5}
                className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-slate-900 focus:border-blue-500 focus:outline-none focus:ring-4 focus:ring-blue-500/10 dark:border-slate-800 dark:bg-slate-900 dark:text-white transition-all"
                value={editForm.detailedOverview}
                onChange={e => setEditForm(prev => ({ ...prev, detailedOverview: e.target.value }))}
                placeholder="Comprehensive overview of brand, target market and products..."
                required
              />
            </div>

            <div>
              <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Marketing Positioning Statement</label>
              <textarea
                rows={3}
                className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-slate-900 focus:border-blue-500 focus:outline-none focus:ring-4 focus:ring-blue-500/10 dark:border-slate-800 dark:bg-slate-900 dark:text-white transition-all"
                value={editForm.marketingPositioning}
                onChange={e => setEditForm(prev => ({ ...prev, marketingPositioning: e.target.value }))}
                placeholder="For [target audience] who [need], [Brand] is the [category] that [differentiator]..."
                required
              />
            </div>
          </div>

          <div className="flex justify-end gap-3 pt-6 border-t border-slate-200 dark:border-slate-800">
            <button
              type="button"
              onClick={() => setIsEditing(false)}
              className="px-6 py-2.5 rounded-xl border border-slate-200 dark:border-slate-800 text-sm font-bold hover:bg-slate-50 dark:hover:bg-slate-800 transition-all"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSaving}
              className="flex items-center gap-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white px-8 py-2.5 rounded-xl text-sm font-bold shadow-lg disabled:opacity-50 transition-all"
            >
              {isSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
              {isSaving ? 'Saving Overrides...' : 'Save Overrides'}
            </button>
          </div>
        </form>
      ) : summary ? (
        /* DNA Display Canvas */
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className={cardClasses}>
            <span className={labelClasses}>Elevator Pitch (1-2 Sentences)</span>
            <blockquote className="text-xl font-bold text-slate-800 dark:text-slate-100 italic leading-relaxed border-l-4 border-blue-500 pl-4 mt-2">
              "{summary.elevatorPitch}"
            </blockquote>
          </div>

          <div className={cardClasses}>
            <span className={labelClasses}>Marketing Positioning Statement</span>
            <p className="text-slate-700 dark:text-slate-300 font-medium leading-relaxed mt-2 bg-slate-50 dark:bg-slate-900 p-4 rounded-2xl border border-slate-100 dark:border-slate-800">
              {summary.marketingPositioning}
            </p>
          </div>

          <div className={`${cardClasses} md:col-span-2`}>
            <span className={labelClasses}>Short Summary (50-100 Words)</span>
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed mt-2 text-base">
              {summary.shortSummary}
            </p>
          </div>

          <div className={`${cardClasses} md:col-span-2`}>
            <span className={labelClasses}>Detailed Brand DNA Overview</span>
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed mt-2 text-base whitespace-pre-line">
              {summary.detailedOverview}
            </p>
          </div>
        </div>
      ) : (
        /* Empty State */
        <div className="flex flex-col items-center justify-center p-12 text-center rounded-3xl border border-dashed border-slate-300 dark:border-slate-800">
          <Sparkles className="h-10 w-10 text-slate-400 dark:text-slate-600 mb-3 animate-pulse" />
          <h4 className="font-bold text-slate-800 dark:text-slate-200">No Brand DNA Summary Generated</h4>
          <p className="text-sm text-slate-500 dark:text-slate-400 max-w-sm mt-1 mb-6">
            Generate an AI-driven, multi-variant Brand DNA Canvas summarizing your identity, elevator pitch, positioning, and overview.
          </p>
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="flex items-center gap-2 bg-[#2D46FF] hover:bg-blue-600 text-white font-bold px-6 py-3 rounded-xl shadow-md transition-all active:scale-95 disabled:opacity-50"
          >
            {isGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
            {isGenerating ? 'Analyzing Brand...' : 'Generate DNA Canvas'}
          </button>
        </div>
      )}
    </div>
  );
}
