export const plans = {
   month: [
      {
         id: "free",
         name: "Free",
         price: "$0",
         description: "Perfect for exploring the power of AI social media and article writing.",
         features: [
            "5 AI social posts / mo",
            "20 AI blog articles / mo",
            "Max 3,000 words / article",
            "1 Brand Voice profile",
            "Real-time SEO scoring",
            "WordPress & Ghost export",
         ],
         cta: "Get Started Free",
         popular: false,
      },
      {
         id: "starter",
         name: "Starter",
         price: "$29",
         description: "Ideal for growing creators and brands requiring scheduled automation.",
         features: [
            "50 AI social posts / mo",
            "100 AI blog articles / mo",
            "Max 8,000 words / article",
            "5 Brand Voice profiles",
            "Post & Article Scheduling",
            "Topical Cluster mapping",
            "AI Detection Bypass",
            "1-Click CMS Publishing",
         ],
         cta: "Upgrade to Starter",
         popular: true,
      },
      {
         id: "pro",
         name: "Pro",
         price: "$99",
         description: "The complete solution for scaling agencies and high-growth brands.",
         features: [
            "Unlimited AI social posts",
            "Unlimited AI blog articles",
            "No word count limits",
            "Unlimited Brand Voices",
            "Team Collaboration & Seats",
            "Custom AI voice training",
            "Developer API & Webhooks",
            "Dedicated Priority Support",
         ],
         cta: "Upgrade to Pro",
         popular: false,
      },
   ],
   year: [
      {
         id: "free",
         name: "Free",
         price: "$0",
         description: "Perfect for exploring the power of AI social media and article writing.",
         features: [
            "5 AI social posts / mo",
            "20 AI blog articles / mo",
            "Max 3,000 words / article",
            "1 Brand Voice profile",
            "Real-time SEO scoring",
            "WordPress & Ghost export",
         ],
         cta: "Get Started Free",
         popular: false,
      },
      {
         id: "starter",
         name: "Starter",
         price: "$24",
         originalPrice: "$29",
         description: "Ideal for growing creators and brands requiring scheduled automation.",
         features: [
            "50 AI social posts / mo",
            "100 AI blog articles / mo",
            "Max 8,000 words / article",
            "5 Brand Voice profiles",
            "Post & Article Scheduling",
            "Topical Cluster mapping",
            "AI Detection Bypass",
            "1-Click CMS Publishing",
         ],
         cta: "Upgrade to Starter",
         popular: true,
      },
      {
         id: "pro",
         name: "Pro",
         price: "$79",
         originalPrice: "$99",
         description: "The complete solution for scaling agencies and high-growth brands.",
         features: [
            "Unlimited AI social posts",
            "Unlimited AI blog articles",
            "No word count limits",
            "Unlimited Brand Voices",
            "Team Collaboration & Seats",
            "Custom AI voice training",
            "Developer API & Webhooks",
            "Dedicated Priority Support",
         ],
         cta: "Upgrade to Pro",
         popular: false,
      },
   ],
};