import { AIArenaService, SUPPORTED_ARENA_MODELS } from '../ai-arena.service';
import { AIService } from '@/services/ai/ai.service';

jest.mock('@/services/ai/ai.service', () => ({
  AIService: {
    generateResponse: jest.fn(),
  },
}));

jest.mock('@/features/system/services/logger.service', () => ({
  SystemLogger: {
    logActivity: jest.fn(),
    logError: jest.fn(),
  },
}));

describe('AIArenaService', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('getAvailableModels', () => {
    it('returns all 4 supported models with pricing metadata', () => {
      const models = AIArenaService.getAvailableModels();
      expect(models.length).toBe(4);
      expect(models.map((m) => m.id)).toContain('gpt-4o');
      expect(models.map((m) => m.id)).toContain('claude-3-5-sonnet');
      expect(models.map((m) => m.id)).toContain('deepseek-r1');
      expect(models.map((m) => m.id)).toContain('gemini-2-0-flash');
    });
  });

  describe('compareModels', () => {
    it('runs parallel model calls and returns execution telemetry', async () => {
      (AIService.generateResponse as jest.Mock).mockResolvedValue({
        content: 'This is a high-converting output generated by the AI model.',
        usage: { prompt_tokens: 30, completion_tokens: 45, total_tokens: 75 },
      });

      const comparison = await AIArenaService.compareModels({
        businessId: 'biz_arena_123',
        prompt: 'Draft an engaging LinkedIn post',
        models: ['gpt-4o', 'claude-3-5-sonnet'],
      });

      expect(comparison.results.length).toBe(2);
      expect(comparison.results[0].status).toBe('SUCCESS');
      expect(comparison.results[0].estimatedCostUsd).toBeGreaterThanOrEqual(0);
      expect(comparison.recommendedModelId).toBeDefined();
      expect(comparison.fastestModelId).toBeDefined();
      expect(comparison.cheapestModelId).toBeDefined();
    });

    it('handles single model errors gracefully without crashing whole arena batch', async () => {
      (AIService.generateResponse as jest.Mock).mockImplementation((req: any) => {
        if (req?.model === 'deepseek-r1') {
          return Promise.reject(new Error('API Timeout'));
        }
        return Promise.resolve({
          content: 'Valid output',
          usage: { prompt_tokens: 20, completion_tokens: 30, total_tokens: 50 },
        });
      });

      const comparison = await AIArenaService.compareModels({
        businessId: 'biz_arena_123',
        prompt: 'Solve analytical equation',
        models: ['gpt-4o', 'deepseek-r1'],
      });

      expect(comparison.results.length).toBe(2);
      const gptRes = comparison.results.find((r) => r.modelId === 'gpt-4o');
      const dsRes = comparison.results.find((r) => r.modelId === 'deepseek-r1');

      expect(gptRes?.status).toBe('SUCCESS');
      expect(dsRes?.status).toBe('ERROR');
      expect(dsRes?.errorMessage).toBe('API Timeout');
    });
  });
});
